In [2]:
import numpy as np
import pandas as pd

In [3]:
def load_data(path, header):
    df = pd.read_csv(path, header = header)
    return df

In [6]:
# load insurance data with features {age, sex, bmi, children, smoker, region } and target charges
insurance_df = load_data("data/insurance.csv", header=0)

In [16]:
insurance_df

age     sex     bmi  children smoker     region      charges  sex_int  \
0      19  female  27.900         0    yes  southwest  16884.92400        0   
1      18    male  33.770         1     no  southeast   1725.55230        1   
2      28    male  33.000         3     no  southeast   4449.46200        1   
3      33    male  22.705         0     no  northwest  21984.47061        1   
4      32    male  28.880         0     no  northwest   3866.85520        1   
...   ...     ...     ...       ...    ...        ...          ...      ...   
1333   50    male  30.970         3     no  northwest  10600.54830        1   
1334   18  female  31.920         0     no  northeast   2205.98080        0   
1335   18  female  36.850         0     no  southeast   1629.83350        0   
1336   21  female  25.800         0     no  southwest   2007.94500        0   
1337   61  female  29.070         0    yes  northwest  29141.36030        0   

      region_int  smoker_int  
0              3           1  
1              2           0  
2              2           0  
3              1           0  
4              1           0  
...          ...         ...  
1333           1           0  
1334           0           0  
1335           2           0  
1336           3           0  
1337           1           1  

[1338 rows x 10 columns]

In [15]:
#Convert string categories to integers 
insurance_df['sex_int'] = insurance_df['sex'].map({'female': 0, 'male': 1})
insurance_df['region_int'] = insurance_df['region'].map({'northeast': 0, 'northwest': 1, 'southeast' : 2, 'southwest': 3})
insurance_df['smoker_int'] = insurance_df['smoker'].map({'no': 0, 'yes': 1})

In [48]:
#Extract feature columns and convert to numpy matrix
regression_df = insurance_df[['age', 'bmi', 'children', 'sex_int', 'region_int', 'smoker_int']]
X_raw = regression_df.values

In [100]:
#Create theta with initially random values
theta = np.random.randn(X_raw.shape[1] + 1)

#Target values
y = insurance_df['charges']

In [58]:
# Prepend column of ones for x0
X = np.column_stack((np.ones(X.shape[0]), X_raw))


In [135]:
np.dot(X_small, theta)

array([-10.3211136 ,  -7.51550413])

In [132]:
X_small = X[0:2, :]
y_small = y[0:2]

In [64]:
def mse_cost_function(x, y, theta):
    #number of examples
    m = x.shape[0]
    # Projected target values
    h_theta = np.dot(x, theta)
    return (1/(2*m)) * np.sum((h_theta - y)**2)
    

In [65]:
mse_cost_function(X, y, theta)

160295726.91393274

In [66]:
theta.size

7

In [141]:
def gradient_descent(x, y, theta):
    theta_new = theta
    theta_temp = np.zeros(theta.size)
    alpha = 0.01
    max_iters = 1
    m = x.shape[0]
    
    
    for j in range(0, max_iters):
        #Update each theta
        for i in range (0, theta_new.size):
            h_theta = np.dot(x, theta_new)
            print(h_theta-y)
            theta_temp[i] = theta_new[i] - alpha*(1/m)*np.sum((h_theta-y)*x[:,i])
        #Set theta_new to new values after simaltaneously updating
        theta_new = theta_temp
        
    #theta = theta_temp
    return theta_temp

In [142]:
X[:, 0]

array([1., 1., 1., ..., 1., 1., 1.])

In [143]:
h_theta = np.dot(X, theta_new)

h_theta-y

0       1.709938e+06
1       2.246553e+06
2       1.983515e+06
3       1.144898e+06
4       1.672599e+06
            ...     
1333    1.481401e+06
1334    2.224966e+06
1335    2.515739e+06
1336    1.530935e+06
1337    1.157560e+06
Name: charges, Length: 1338, dtype: float64

In [144]:
theta_new = gradient_descent(X_small, y_small, np.zeros(7))

0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64
0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64
0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64
0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64
0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64
0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64
0   -16884.9240
1    -1725.5523
Name: charges, dtype: float64


In [140]:
theta_new

array([  -963.72313583, -17523.97846457,  79685.68065744, -11858.48654996,
       -11799.15097841, -51326.78428665,  -8508.2270007 ])

In [114]:
theta_new

array([-1.01740084e+37, -3.61801798e+38,  4.35376685e+40, -1.45009349e+41,
       -5.91858324e+40, -1.75894265e+41, -1.76441507e+40])